myexcuse/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from excuses.views import show_excuses
from excuses.views import adding_excuses

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^add/$', adding_excuses),
    url(r'^$', show_excuses),
]

excuses/models.py
from django.db import models

# Create your models here.
class Excuse(models.Model):
    provider = models.CharField(max_length=50)
    content = models.CharField(max_length=100)

excuses/views.py
from django.shortcuts import render
from excuses.models import Excuse
import random
from django.http import HttpResponseRedirect
from django import forms
# Create your views here.
class ExcuseForm(forms.ModelForm):
    class Meta:
        model = Excuse
        fields = ['provider', 'content', ]

def show_excuses(request):
    excuses_list = Excuse.objects.all()
    if len(excuses_list) == 0:
        return render(request, 'index.html', {'current_excuse': "Nothing in DB!!!"})
    else:
        e = excuses_list[random.randint(0, len(excuses_list)-1)]
        return render(request, 'index.html', {'current_excuse': e.content, 'current_excuse_provider':e.provider})

def adding_excuses(request):
    if request.method == 'POST':
        form = ExcuseForm(request.POST)
        if form.is_valid():
            new_article = form.save()
            return HttpResponseRedirect('/')

    form = ExcuseForm()
    return render(request, 'add.html', {'form': form})

excuses/templates/add.html
<!DOCTYPE HTML>
<html>
<head>
    <title>Excuses For U</title>
    <meta name="keywords" content="Excuses, Reasons, Lies, Fibs, Blame, Justifications" />
    <meta name="description" content="Any Excuses For Anything Anyone" />
    <style type="text/css">
        * {margin: 0;} 
        html, body {height: 100%; background-color: #000;} 
        form{text-align: left;}
        p{margin: 20px;}
        .wrapper {min-height: 100%; height: auto !important; height: 100%; margin: 0 auto -8em; width: 80%;} 
        .footer, .push {height: 8em;}
        #id_provider{width: 25%; height: 20%; font-size: 36px; background-color: #000; color: #fff; font-weight: bold; border-radius: 15px; border: 5px solid #fff; padding: 10px;}
        #id_content{width: 60%; font-size: 36px; background-color: #000; color: #fff; font-weight: bold; border-radius: 15px; border: 5px solid #fff; padding: 10px; margin-left: 28px;}
        #submit{float: right; font-size: 20px; background-color: #000; color: #fff; font-weight: bold; border-radius: 15px; border: 5px solid #fff; padding: 10px; cursor: pointer;}
    </style>
</head>
<body>
    <div class="wrapper">
        <center style="color: #fff; padding-top: 200px; font-family: Courier; font-size: 48px; font-weight: bold;">
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="submit" type="submit" value="Add Your Excuses" />
            </form>
        </center>
    </div>
    <div class="footer">
     <center style="color: #333; font-family: Courier; font-size: 24px; font-weight: bold;">
        <a href="/" rel="nofollow" style="text-decoration: none; color: #fff;">BACK</a>
     </center>
    </div>
</body>
</html>

excuses/templates/index.html
<!DOCTYPE HTML>
<html>
<head>
    <title>Excuses For U</title>
    <meta name="keywords" content="Excuses, Reasons, Lies, Fibs, Blame, Justifications" />
    <meta name="description" content="Any Excuses For Anything Anyone" />
    <style type="text/css">
        * {margin: 0;} 
        html, body {height: 100%; background-color: #000;} 
        .wrapper {min-height: 100%; height: auto !important; height: 100%; margin: 0 auto -8em; width: 80%;} 
        .footer, .push {height: 8em;}
    </style>
</head>
<body>
    <div class="wrapper">
        <center style="color: #fff; padding-top: 200px; font-family: Courier; font-size: 60px; font-weight: bold;">
            <a href="/" rel="nofollow" style="text-decoration: none; color: #fff;">{{current_excuse}}</a>
        </center>
            <a href="/" rel="nofollow" style="float:right; font-family: Courier; font-size: 20px; text-decoration: none; color: #fff;">{{current_excuse_provider}}</a>
    </div>
    <div class="footer">
     <center style="color: #333; font-family: Courier; font-size: 24px; font-weight: bold;">
        <a href="/add" rel="nofollow" style="text-decoration: none; color: #fff;">Add Your Excuses</a>
     </center>
    </div>
</body>
</html>